name: Request access to richardw7.github.io
description: Paid access request for richardw7.github.io.
title: "Access request: richardw7.github.io"
labels: ["access-request"]

body:
  - type: markdown
    attributes:
      value: |
        <!-- entitlement_id: acd2c89b-4652-430e-ae76-c31624b66b72 -->
        You are requesting paid access to **richardw7.github.io**.
        After submitting this issue, you will receive a payment link.

  - type: dropdown
    id: entitlement_id
    attributes:
      label: Entitlement ID
      description: This is selected automatically. Do not change it.
      options:
        - acd2c89b-4652-430e-ae76-c31624b66b72
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Your email (optional)
      description: We'll only use this if we need to contact you about the request.
      placeholder: you@example.com
    validations:
      required: false
