name: Request access to chart-generator-backend
description: Paid access request for chart-generator-backend.
title: "Access request: chart-generator-backend"
labels: ["access-request"]

body:
  - type: markdown
    attributes:
      value: |
        <!-- entitlement_id: 226d9322-44a0-418e-9ed5-92fe46ca3ce5 -->
        You are requesting paid access to **chart-generator-backend**.
        After submitting this issue, you will receive a payment link.

  - type: dropdown
    id: entitlement_id
    attributes:
      label: Entitlement ID
      description: This is selected automatically. Do not change it.
      options:
        - 226d9322-44a0-418e-9ed5-92fe46ca3ce5
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Your email (optional)
      description: We'll only use this if we need to contact you about the request.
      placeholder: you@example.com
    validations:
      required: false
